### PR TITLE
Support of .net core 3.0 global tooling

### LINKED ISSUE #70: Add .NET Core 3.0 global tool support
.NET Core 2.* tools can't be installed on the .NET Core 3.0 runtime.

### PR DESCRIPTION
**Pull request by IgorFedchenko**
Close #70

### CODE REVIEW

**Comment by IgorFedchenko** [comment]
I have tested this with building package to local directory, and then installing it from inside of docker image. Seems like adding `netcoreapp3.0` target solves the problem - global tool may be installed from both `v2.1` and `v.3.0`.

Is it what was required in issue #70 ?

**Comment by IgorFedchenko** [comment]
Tests are failing because they are executed by `v2.1`, which of course can not build the project.

**Comment by IgorFedchenko** [comment]
By the way, here is how you can test this:

1. Pack new nuget with version  0.1.8 to local dir (you will need `.net core 3.0` installed): 
`dotnet pack -o nupkg`
2. Get into .net core 3.0 docker image:
`docker run  -v /path/to/project:/incrementalist -it mcr.microsoft.com/dotnet/core/sdk:3.0`
3. Try installing the tool from local nuget source: 
```
root> cd incrementalist
root> dotnet tool install -g --add-source ./nupkg Incrementalist.Cmd --version 0.1.8
root> incrementalist --version
```

Should work well.

**Comment by Aaronontheweb** [comment]
@IgorFedchenko I think it's also our build system needing to be upgraded to support .NET Core 3.0 compilation - I'll take a look at it. We have some standard templates we use for doing this stuff and I just recently upgraded them to use .NET Core 3.0 a couple of weeks ago: https://github.com/petabridge/Petabridge.App

**Pull request closed without merging**
