### PR TITLE
Imported project files modifications check

### LINKED ISSUE #68: Need to be able to detect changes in `.props` files referenced by projects
In [Akka.NET](https://github.com/akkadotnet/akka.net) for instance, we have a `common.props` file in the `src` folder that is referenced by virtually every project in the solution. When that file changes, _all_ of those affected projects should be detected in the change. 

Currently, these types of changes can't be detected through Roslyn alone - or at least through the APIs we're using. We're going to need to develop some way of determining whether or not the content related to a specific project has changed or not, even if the project file itself wasn't directly modified. 

So the right place to probably change this is our modification detection code (currently done solely via which files show up in the `git diff`,) rather than through our Roslyn analysis.

### PR DESCRIPTION
**Pull request by IgorFedchenko**
Close #68 

The way this is going to work is getting all imported files paths from `<Image Project="path/to/props">` tags of all projects in solution, and then checking if any of them were modified.

Will keep PR in draft until add some tests to verify this works well.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Sorry about this @IgorFedchenko - looks like I needed to update the Azure DevOps connection. Just did that. If you push 1 more commit that should trigger PR validation.

**Comment by IgorFedchenko** [comment]
Sure, no problem

**Comment by IgorFedchenko** [comment]
@Aaronontheweb I could add more tests for multiple imports cases, maybe multiple projects, etc - but there should not be much difference in how the code works in this cases

**Comment by IgorFedchenko** [comment]
Seems like tests failed, but that is because it thinks that my "SampleProject.csproj" file, generated during tests execution, is a real project. Maybe it should ignore all files under `bin` directory? 

Or, I will just add cleanup code now

**Comment by Aaronontheweb** [comment]
Thanks @IgorFedchenko! I'll try running this locally and take a look at it. Appreciate the hard work.

**Comment by Aaronontheweb** [comment]
@IgorFedchenko just validated this on the Akka.NET solution itself, which is where we're going to see this in action first. Worked like a charm. Thank you!

**Pull request merged**
