### PR TITLE
Fsharp projects change tracking

### LINKED ISSUE #69: Need to be able to detect changes in F# projects
https://github.com/akkadotnet/akka.net/pull/3982 - only a `.fsproj` file was changed. We were not able to detect those changes and thus, didn't run any builds.

### PR DESCRIPTION
**Pull request by IgorFedchenko**
Close #69 

This PR is based on currently waiting for merge #71 PR, so better to merge that one first.

Creating in draft state because test is added, but implementation is missing

### CODE REVIEW

**Comment by IgorFedchenko** [comment]
@Aaronontheweb The issue here is that when Roslyn is loading solution with `_workspace.OpenSolutionAsync(slnName, _progress, CancellationToken)` it does not see `.fsproj` as a project in solution. In my test there are two projects, but after solution loading it is reporting only one project.
Will try to figure out why is that.

**Comment by IgorFedchenko** [comment]
All right, so, at least on my machine, I am getting `_workspace.Services.IsSupported(LanguageNames.FSharp) == false`. But I am able to load F# projects in IDE of course.

Looking at some [answers](https://stackoverflow.com/a/47239729/3094849) at StackOverflow it seems like Roslyn does not fully support F# - at least this is a possible reason of errors we have. I have added logging of solution loading errors (`_workspace.WorkspaceFailed` event), and initially it was saying that `.fsproj` is not assigned to any known language, and after explicit assigning to `LanguageNames.FSharp` it started giving `F# is not supported` error.

With that said, in this project we actually do not need to manipulate with `F#` itself - we only need to keep track of project graph and be able to detect project directories/imports. 
That is why I used a small hack - assigned `fsproj` project extension to `LanguageNames.CSharp`. With this, it is loading project with no issues. This will also allow to assign `.fs` F# source code file changed to the right project - because now F# project will be recognized and source code files will be assigned to the project.

@Aaronontheweb what do you think about that? I have also tried to update `Microsoft.CodeAnalysis.Workspaces.MSBuild` nuget package version from `3.0.0` to `3.3.1` but it did not help. Neither I could find a way to register F# as a supported service (and link to SO answer above might explain that).

**Comment by Aaronontheweb** [comment]
> Looking at some answers at StackOverflow it seems like Roslyn does not fully support F# - at least this is a possible reason of errors we have. I have added logging of solution loading errors (_workspace.WorkspaceFailed event), and initially it was saying that .fsproj is not assigned to any known language, and after explicit assigning to LanguageNames.FSharp it started giving F# is not supported error. With debugging of external sources, I can see that it is because there is no workspace.Services that are assigned to F#.

That's annoying :( - not much we can do about the Roslyn tooling itself though.

> With that said, in this project we actually do not need to manipulate with F# itself - we only need to keep track of project graph and be able to detect project directories/imports.
That is why I used a small hack - assigned fsproj project extension to LanguageNames.CSharp. With this, it is loading project with no issues. This will also allow to assign .fs F# source code file changed to the right project - because now F# project will be recognized and source code files will be assigned to the project.

I think your hack is fine for the time being - better than what we have today. But could you open an issue to do this the "right" way, registering F# as a service with Roslyn?

**Comment by Aaronontheweb** [comment]
Also, looks like my merge conflict resolution may have broken the build here... Let me look at that

**Comment by Aaronontheweb** [comment]
Should have that fixed now - just rebased everything and tested it locally.

**Comment by IgorFedchenko** [comment]
> But could you open an issue to do this the "right" way, registering F# as a service with Roslyn?

Sure, created [issue](https://github.com/petabridge/Incrementalist/issues/85) for that.

**Pull request merged**
